#!/usr/bin/env bash
# flash.sh — Flash ESP32 firmware to one or more boards.
#
# Run on the Pi (or anywhere esptool.py is available and boards are connected).
#
# Usage:
#   ./flash.sh                          # flash all /dev/esp_port_* devices
#   ./flash.sh /dev/esp_port_0          # flash one specific port
#   ./flash.sh /dev/esp_port_0 /dev/esp_port_1   # flash specific ports
#
# The script reads the flat binaries from ./esp/ (produced by build.sh):
#   esp/firmware.bin           — application image
#   esp/bootloader.bin         — bootloader
#   esp/partition-table.bin    — partition table
#
# It also honours esp/flasher_args.json if present (generated by ESP-IDF
# build), which carries the chip-correct flash addresses.

set -e
cd "$(dirname "$0")"

ESP_DIR="./esp"
BAUD="${FLASH_BAUD:-460800}"   # Override with: FLASH_BAUD=921600 ./flash.sh

# ── Locate firmware binaries ─────────────────────────────────────────────── #

FW="$ESP_DIR/firmware.bin"
BL="$ESP_DIR/bootloader.bin"
PT="$ESP_DIR/partition-table.bin"

if [ ! -f "$FW" ]; then
    echo "[flash] ERROR: $FW not found. Run ./build.sh first."
    exit 1
fi

# ── Resolve flash addresses ───────────────────────────────────────────────── #
#
# Use flasher_args.json if available (ESP-IDF generated), otherwise fall back
# to the standard ESP32 partition layout.

FLASHER_ARGS="$ESP_DIR/build/flasher_args.json"

if [ -f "$FLASHER_ARGS" ] && command -v python3 &>/dev/null; then
    # Parse addresses from the JSON.
    ADDR_FW=$(python3 -c "
import json, sys
with open('$FLASHER_ARGS') as f:
    d = json.load(f)
for addr, path in d.get('flash_files', {}).items():
    if 'firmware' in path or '.bin' in path and 'bootloader' not in path and 'partition' not in path:
        print(addr); sys.exit(0)
print('0x10000')")

    ADDR_BL=$(python3 -c "
import json, sys
with open('$FLASHER_ARGS') as f:
    d = json.load(f)
for addr, path in d.get('flash_files', {}).items():
    if 'bootloader' in path:
        print(addr); sys.exit(0)
print('0x1000')")

    ADDR_PT=$(python3 -c "
import json, sys
with open('$FLASHER_ARGS') as f:
    d = json.load(f)
for addr, path in d.get('flash_files', {}).items():
    if 'partition' in path:
        print(addr); sys.exit(0)
print('0x8000')")
else
    # Standard ESP32 defaults.
    ADDR_BL="0x1000"
    ADDR_PT="0x8000"
    ADDR_FW="0x10000"
fi

echo "[flash] Addresses: bootloader=$ADDR_BL  partition-table=$ADDR_PT  firmware=$ADDR_FW"

# ── Resolve target ports ─────────────────────────────────────────────────── #

if [ "$#" -gt 0 ]; then
    PORTS=("$@")
else
    # Auto-discover udev-managed symlinks.
    PORTS=()
    for p in /dev/esp_port_*; do
        [ -e "$p" ] && PORTS+=("$p")
    done
    if [ "${#PORTS[@]}" -eq 0 ]; then
        echo "[flash] No ports specified and no /dev/esp_port_* devices found."
        exit 1
    fi
fi

echo "[flash] Flashing ${#PORTS[@]} board(s): ${PORTS[*]}"

# ── Flash each board ─────────────────────────────────────────────────────── #

FAILED=()
for PORT in "${PORTS[@]}"; do
    echo ""
    echo "[flash] ── $PORT ──────────────────────────────────────────────────"

    FLASH_CMD=(
        esptool.py
        --chip  esp32
        --port  "$PORT"
        --baud  "$BAUD"
        write_flash
        --flash_mode  dio
        --flash_freq  40m
        --flash_size  detect
    )

    # Only include binaries that exist.
    [ -f "$BL" ] && FLASH_CMD+=("$ADDR_BL" "$BL")
    [ -f "$PT" ] && FLASH_CMD+=("$ADDR_PT" "$PT")
    FLASH_CMD+=("$ADDR_FW" "$FW")

    if "${FLASH_CMD[@]}"; then
        echo "[flash] $PORT — OK"
    else
        echo "[flash] $PORT — FAILED"
        FAILED+=("$PORT")
    fi
done

echo ""
if [ "${#FAILED[@]}" -gt 0 ]; then
    echo "[flash] FAILED ports: ${FAILED[*]}"
    exit 1
else
    echo "[flash] All boards flashed successfully."
fi
