"""ESP32 firmware flashing interface.

Calls esptool.py to flash the three firmware binaries (bootloader,
partition table, application) onto each connected ESP board in sequence.

Reads binaries from the esp/ directory alongside the source C file.
Called by the Pi either manually (flash.sh) or via a host MQTT command.

Flash address reference:
    ESP32 / ESP32-S2:  bootloader @ 0x1000
    ESP32-S3 / C3 / H2: bootloader @ 0x0
    Partition table:   always @ 0x8000
    Application:       always @ 0x10000

The correct addresses for the current build are stored in
esp/flasher_args.json, generated by build.sh from the ESP-IDF output.
"""

import asyncio
import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Default flash addresses for ESP32 (original). Overridden by flasher_args.json.
_DEFAULT_ADDRS = {
    "bootloader":       "0x1000",
    "partition_table":  "0x8000",
    "firmware":         "0x10000",
}

_ESPTOOL_BAUD = 921600


class FlashManager:
    """Flashes firmware onto connected ESP boards.

    Args:
        esp_dir: Path to the esp/ firmware workspace directory.
    """

    def __init__(self, esp_dir: str | Path) -> None:
        self._esp_dir = Path(esp_dir)

    # ======================== Public ======================== #

    async def flash_all(self, ports: list[str]) -> dict[str, bool]:
        """Flash all given ports sequentially.

        Args:
            ports: List of device paths (e.g. ['/dev/esp_port_0', ...]).

        Returns:
            Dict mapping each port to True (success) / False (failure).
        """
        addrs = self._load_flash_addresses()
        results: dict[str, bool] = {}
        for port in ports:
            results[port] = await self._flash_one(port, addrs)
        return results

    async def flash_port(self, port: str) -> bool:
        """Flash a single board.

        Returns True on success, False on failure.
        """
        addrs = self._load_flash_addresses()
        return await self._flash_one(port, addrs)

    # ======================== Internal ======================== #

    def _load_flash_addresses(self) -> dict[str, str]:
        """Read flash addresses from flasher_args.json if present.

        Falls back to ESP32 defaults if the file is missing or malformed.
        """
        args_path = self._esp_dir / "flasher_args.json"
        if not args_path.exists():
            logger.warning(
                "flasher_args.json not found — using ESP32 default addresses. "
                "Run build.sh first to generate correct addresses for your chip."
            )
            return dict(_DEFAULT_ADDRS)

        try:
            with open(args_path) as f:
                data = json.load(f)
            flash_files = data.get("flash_files", {})
            # Map known filenames to their addresses.
            addrs = dict(_DEFAULT_ADDRS)
            for addr, path in flash_files.items():
                name = Path(path).name
                if "bootloader" in name:
                    addrs["bootloader"] = addr
                elif "partition-table" in name or "partition_table" in name:
                    addrs["partition_table"] = addr
                else:
                    addrs["firmware"] = addr
            return addrs
        except Exception as e:
            logger.error("Failed to parse flasher_args.json: %s — using defaults", e)
            return dict(_DEFAULT_ADDRS)

    def _binary_paths(self) -> tuple[Path, Path, Path]:
        """Return (bootloader, partition_table, firmware) binary paths."""
        return (
            self._esp_dir / "bootloader.bin",
            self._esp_dir / "partition-table.bin",
            self._esp_dir / "firmware.bin",
        )

    def _check_binaries(self) -> list[str]:
        """Return a list of missing binary filenames."""
        missing = []
        for p in self._binary_paths():
            if not p.exists():
                missing.append(p.name)
        return missing

    async def _flash_one(self, port: str, addrs: dict[str, str]) -> bool:
        """Run esptool.py for a single port."""
        missing = self._check_binaries()
        if missing:
            logger.error(
                "Flash aborted — missing binaries: %s. Run build.sh first.", missing
            )
            return False

        bootloader, partition_table, firmware = self._binary_paths()

        cmd = [
            "esptool.py",
            "--port",   port,
            "--baud",   str(_ESPTOOL_BAUD),
            "--chip",   "auto",
            "--before", "default_reset",
            "--after",  "hard_reset",
            "write_flash",
            addrs["bootloader"],    str(bootloader),
            addrs["partition_table"], str(partition_table),
            addrs["firmware"],      str(firmware),
        ]

        logger.info("Flashing board on %s ...", port)
        logger.debug("esptool cmd: %s", " ".join(cmd))

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
            stdout, _ = await proc.communicate()
            output = stdout.decode(errors="replace") if stdout else ""

            if proc.returncode == 0:
                logger.info("Flash OK: %s", port)
                return True
            else:
                logger.error("Flash FAILED: %s\n%s", port, output)
                return False

        except FileNotFoundError:
            logger.error(
                "esptool.py not found. Install it: pip install esptool"
            )
            return False
        except Exception as e:
            logger.error("Flash error on %s: %s", port, e)
            return False
