"""udev rule generator for stable ESP board port naming.

Run this utility ONCE during Pi setup (not at runtime) to create udev
rules that map each physical USB port to a fixed symlink. This ensures
/dev/esp_port_0 always refers to the same physical socket regardless
of plug order or reboot.

Usage (run on the Pi as root):
    sudo python3 -m base.esp.udev

Or call generate_rules() programmatically and install the output.

How it works:
    Each physical USB port has a stable kernel path (e.g. "1-1.2").
    udev rules bind that path to a named symlink. The board plugged into
    socket "1-1.2" will always appear as /dev/esp_port_0 — even if the
    kernel assigns it a different ttyUSB number on the next boot.

Steps:
    1. Plug ESP boards in one at a time, noting which physical socket
       each goes into.
    2. Run this script — it lists all currently detected ESP-like devices
       with their USB paths.
    3. Confirm the mapping looks correct.
    4. Install the generated rule file and reload udev.
"""

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

UDEV_RULE_PATH = Path("/etc/udev/rules.d/99-esp-boards.rules")
SYMLINK_PREFIX = "esp_port_"

# USB vendor IDs common to ESP32 USB-UART bridge chips.
_KNOWN_VIDS = {
    "10c4",  # Silicon Labs CP210x
    "1a86",  # QinHeng Electronics CH340
    "0403",  # FTDI
    "303a",  # Espressif native USB (ESP32-S3, C3)
}


def detect_connected_boards() -> list[dict[str, str]]:
    """Return a list of detected ESP-like serial devices with their USB paths.

    Each entry: {"device": "/dev/ttyUSBN", "devpath": "1-1.2", "vid": "10c4"}
    """
    boards = []
    tty_devices = list(Path("/sys/class/tty").glob("ttyUSB*")) + \
                  list(Path("/sys/class/tty").glob("ttyACM*"))

    for tty in sorted(tty_devices):
        try:
            # Resolve the full sysfs path for this tty device.
            sysfs = (tty / "device").resolve()

            # Read vendor ID.
            vid_path = sysfs.parent / "idVendor"
            if not vid_path.exists():
                vid_path = sysfs / "idVendor"
            vid = vid_path.read_text().strip().lower() if vid_path.exists() else ""

            if vid not in _KNOWN_VIDS:
                continue

            # Read the devpath (stable USB port topology path).
            devpath_path = sysfs.parent / "devpath"
            if not devpath_path.exists():
                devpath_path = sysfs / "devpath"
            devpath = devpath_path.read_text().strip() if devpath_path.exists() else ""

            boards.append({
                "device":  f"/dev/{tty.name}",
                "devpath": devpath,
                "vid":     vid,
            })
        except Exception:
            continue

    return boards


def generate_rules(boards: list[dict[str, str]]) -> str:
    """Generate udev rule file content mapping USB paths to stable symlinks.

    Args:
        boards: List of board dicts from detect_connected_boards().

    Returns:
        String content for the udev rules file.
    """
    lines = [
        '# ESP32 board stable port naming.',
        '# Generated by base/esp/udev.py — do not edit manually.',
        '# Reload with: sudo udevadm control --reload-rules && sudo udevadm trigger',
        '',
    ]
    for i, board in enumerate(boards):
        devpath = board["devpath"]
        symlink = f"{SYMLINK_PREFIX}{i}"
        lines.append(
            f'SUBSYSTEM=="tty", ATTRS{{devpath}}=="{devpath}", '
            f'SYMLINK+="{symlink}"'
        )
        lines.append(f'# Physical port: {devpath}  →  /dev/{symlink}  ({board["device"]})')
        lines.append('')

    return "\n".join(lines)


def install_rules(rules_content: str) -> bool:
    """Write the rules file and reload udev.

    Returns True on success. Must be run as root.
    """
    try:
        UDEV_RULE_PATH.write_text(rules_content)
        logger.info("udev rules written to %s", UDEV_RULE_PATH)

        subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
        subprocess.run(["udevadm", "trigger"], check=True)
        logger.info("udev rules reloaded")
        return True
    except PermissionError:
        logger.error("Permission denied — run as root: sudo python3 -m base.esp.udev")
        return False
    except Exception as e:
        logger.error("Failed to install udev rules: %s", e)
        return False


# ======================== CLI Entry Point ======================== #

if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")

    print("Scanning for connected ESP boards...")
    boards = detect_connected_boards()

    if not boards:
        print("No ESP-like USB serial devices detected.")
        print("Connect your boards and try again.")
        sys.exit(1)

    print(f"\nFound {len(boards)} device(s):\n")
    for i, b in enumerate(boards):
        print(f"  [{i}] /dev/esp_port_{i}  ←  {b['device']}  (USB path: {b['devpath']}, VID: {b['vid']})")

    print()
    confirm = input("Install these udev rules? [y/N] ").strip().lower()
    if confirm != "y":
        print("Aborted.")
        sys.exit(0)

    rules = generate_rules(boards)
    print("\nGenerated rules:\n")
    print(rules)

    success = install_rules(rules)
    sys.exit(0 if success else 1)
