"""Project-specific configuration models.

Extend BaseClientConfig and BaseHostConfig with settings unique
to your project. Add matching sections to your TOML config files.
"""

from pydantic import BaseModel
from base.config import BaseClientConfig, BaseHostConfig


# ======================== ESP Port Config ======================== #

class ESPPortConfig(BaseModel):
    """Configuration for a single ESP board connection.

    symlink:   The stable udev symlink for this board's USB port.
               Generated by base/esp/udev.py during Pi setup.
               e.g. '/dev/esp_port_0'

    baud_rate: Serial communication speed. Must match the firmware's
               UART_BAUD constant in esp/main.c.
    """
    symlink:   str = ""
    baud_rate: int = 921600


# ======================== ESP Config ======================== #

class ESPConfig(BaseModel):
    """ESP board management settings for the client.

    ports:              List of connected ESP boards. If empty, the runtime
                        will auto-discover all present /dev/esp_port_* devices.

    heartbeat_interval: How often (seconds) the Pi polls each board for status.

    esp_dir:            Path to the esp/ firmware workspace directory,
                        relative to the project root. Used by FlashManager
                        to locate firmware binaries.
    """
    ports:              list[ESPPortConfig] = []
    heartbeat_interval: float              = 5.0
    esp_dir:            str                = "./esp"


# ======================== Project Client Config ======================== #

class ProjectClientConfig(BaseClientConfig):
    """Client configuration for this project.

    Extends BaseClientConfig which already provides:
        pid, mqtt, database, service

    Add your project-specific fields below.
    """
    esp: ESPConfig = ESPConfig()


# ======================== Storage Settings ======================== #

class StorageConfig(BaseModel):
    """Host-side data storage settings."""
    max_records:         int   = 10000
    checkpoint_interval: float = 60.0


# ======================== Sync Settings ======================== #

class SyncConfig(BaseModel):
    """Host-to-client sync interval settings."""
    clock_sync_interval: float = 3600.0
    pi_check_interval:   float = 300.0


# ======================== Project Host Config ======================== #

class ProjectHostConfig(BaseHostConfig):
    """Host configuration for this project.

    Extends BaseHostConfig which already provides:
        mqtt, database, api, service, clients

    Add your project-specific fields below.
    """
    storage: StorageConfig = StorageConfig()
    sync:    SyncConfig    = SyncConfig()
